== 概述

本文档是GitHub官方REST API v3文档的翻译。
如果您有任何问题或要求，请联系 https://github.com/contact[GitHub支持]。

... <<CurrentVersion,当前版本>>
... <<Schema,结构>>
... <<Authentication,认证>>
... <<Parameters,参数>>
... <<RootEndpoint,根端点>>
... <<GraphQLGlobalNodeIDs,GraphQL全局节点IDs>>
... <<ClientErrors,客户端错误>>
... <<HTTPRedirects,HTTP redirects>>
... <<HTTPVerbs,HTTP verbs>>
... <<Hypermedia,Hypermedia>>
... <<Pagination,Pagination>>
... <<RateLimiting,Rate limiting>>
... <<UserAgentRequired,User agent required>>
... <<ConditionalRequests,Conditional requests>>
... <<CrossOriginResourceSharing,Cross origin resource sharing>>
... <<JSON-PCallbacks,JSON-P callbacks>>
... <<Timezones,Timezones>>


[[CurrentVersion]]
=== 当前版本

默认情况下，对 `+https://api.github.com+` 的所有请求都会发送到REST API的v3 https://developer.github.com/v3/versions[版本]。
我们建议您通过 https://developer.github.com/v3/media/#request-specific-version[`+Accept+` 标记请求头明确请求此版本]。

....
Accept: application/vnd.github.v3+json
....

有关GitHub的GraphQL API v4的信息，请参阅 https://developer.github.com/v4[v4文档]。
有关迁移到GraphQL的信息，请参阅“ https://developer.github.com/v4/guides/migrating-from-rest/[从REST迁移] ”。

[[Schema]]
=== 结构

所有API访问均使用HTTPS协议，并可从 `+https://api.github.com+` 进行访问。 所有数据都以JSON的形式发送和接收。

----
curl -i https://api.github.com/users/octocat/orgs

HTTP/1.1 200 OK
Server: nginx
Date: Fri, 12 Oct 2012 23:33:14 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Status: 200 OK
ETag: "a00049ba79152d03380c34652f2cb612"
X-GitHub-Media-Type: github.v3
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4987
X-RateLimit-Reset: 1350085394
Content-Length: 5
Cache-Control: max-age=0, private, must-revalidate
X-Content-Type-Options: nosniff
----

空白字段包含为 `null` 而不是被省略。

所有时间戳均以ISO 8601格式返回:

....
YYYY-MM-DDTHH:MM:SSZ
....

有关时间戳中时区的详细信息，请参阅此 https://developer.github.com/v3/#timezones[部分]。

==== 结构摘要

获取资源列表时，响应包括该资源的属性子集。 这是资源的“摘要”表示。
(某些属性在API上提供的计算成本很高。出于性能原因，摘要表示会排除这些属性。要获取这些属性，请获取“详细”资源。)

例如:获取存储库列表后，您将获得每个存储库的摘要表示。 在这里，我们获取 https://github.com/octokit[octokit] 组织拥有的存储库列表：

....
GET /orgs/octokit/repos
....

==== 结构详情

获取单个资源时，响应通常包括该资源的所有属性。 这是资源的“详细”表示。
(请注意，授权有时会影响表示中包含的详细信息量。)

例如:获取单个存储库后，您将获得存储库的详细表示。 在这里，我们获取 https://github.com/octokit/octokit.rb[octokit/octokit.rb] 存储库：

....
GET /repos/octokit/octokit.rb
....

该文档提供了每种API方法的示例响应。 示例响应说明了该方法返回的所有属性。

[[Authentication]]
=== 认证

有三种方法可以通过GitHub API v3进行身份验证。 在某些地方，需要身份验证的请求将返回 `404 Not Found` ，而不是 `403 Forbidden` 。 这是为了防止私有存储库意外泄露给未经授权的用户。

==== 基本认证方式

....
curl -u "username" https://api.github.com
....

==== OAuth2 token方式 (在header中发送)

....
curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com
....

==== OAuth2 token方式 (参数形式发送)

....
curl https://api.github.com/?access_token=OAUTH-TOKEN
....

阅读 https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/[有关OAuth2的更多信息] 。
请注意，对于非网站的应用程序，可以 https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization[通过编程方式获取] OAuth2令牌。

==== OAuth2 key/secret方式

....
curl 'https://api.github.com/users/whatever?client_id=xxxx&client_secret=yyyy'
....

这种方式仅被用于服务器到服务器方案。 不要将OAuth应用程序的客户端密钥泄露给您的用户。

阅读 https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications[更多关于未经验证的速率限制]。

==== 登录失败的限制

使用无效凭据进行身份验证将返回 `401 Unauthorized`：

....
curl -i https://api.github.com -u foo:bar

HTTP/1.1 401 Unauthorized
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
....

在短时间内检测到多个具有无效凭据的请求后，API将暂时拒绝该用户的所有身份验证尝试（包括具有有效凭据的身份验证）和 `403 Forbidden`：

....
curl -i https://api.github.com -u valid_username:valid_password

HTTP/1.1 403 Forbidden
{
  "message": "Maximum number of login attempts exceeded. Please try again later.",
  "documentation_url": "https://developer.github.com/v3"
}
....

[[Parameters]]
=== 参数

许多API方法都采用可选参数。 对于GET请求，未包含在路径中任何字符串都可以作为参数传递：

....
curl -i "https://api.github.com/repos/vmg/redcarpet/issues?state=closed"
....

在此示例中，为路径中的 `vmg` 和 `redcarpet` 参数提供 `:owner` 和 `:repo` 的值，而在查询字符串中传递 `:state` 。

对于 `POST` ， `PATCH` ， `PUT` 和 `DELETE` 请求，URL中未包含的参数应编码为JSON，其Content-Type为'application/json':

....
curl -i -u username -d '{"scopes":["public_repo"]}' https://api.github.com/authorizations
....

[[RootEndpoint]]
=== 根端点

您可以向根端点发出 `GET` 请求，以获取REST API v3支持的所有端点类别：

....
curl https://api.github.com
....

[[GraphQLGlobalNodeIDs]]
=== GraphQL全局节点IDs

有关如何通过REST API v3查找node_ids并在GraphQL操作中使用它们的详细信息，请参阅“ https://developer.github.com/v4/guides/using-global-node-ids[使用全局节点IDs] ”指南。

[[ClientErrors]]
=== 客户端错误

接收请求主体的API调用有三种可能的客户端错误类型：

1.发送无效的JSON会返回 `400 Bad Request`。

....
HTTP/1.1 400 Bad Request
Content-Length: 35

{"message":"Problems parsing JSON"}
....

2.发送错误类型的JSON值会返回 `400 Bad Request`。

....
HTTP/1.1 400 Bad Request
Content-Length: 40

{"message":"Body should be a JSON object"}
....

3.发送无效字段将返回 `422 Unprocessable Entity`。

....
HTTP/1.1 422 Unprocessable Entity
Content-Length: 149

{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Issue",
      "field": "title",
      "code": "missing_field"
    }
  ]
}
....

所有错误对象都具有资源和字段属性，以便客户端可以知道问题所在。 还有一个错误代码，让您知道该字段有什么问题。 这些是有可能出现的验证错误代码：

All error objects have resource and field properties so that your client can tell what the problem is. There's also an error code to let you know what is wrong with the field. These are the possible validation error codes:

[%header,cols=2*]
|===
|错误名
|描述

|missing
|这意味着资源不存在。

|missing_field
|这意味着尚未设置资源上的必填字段。

|invalid
|这意味着字段的格式无效。 该资源的文档应该能够为您提供更具体的信息。

|already_exists
|这意味着另一个资源与此字段具有相同的值。 这可能发生在必须具有某些唯一键（例如名为Label）的资源中。
|===

资源也可能发送自定义验证错误（ `代码` 是 `自定义` 的）。 自定义错误将始终有描述错误的 `message` 字段，并且大多数错误还将包括一个 `documentation_url` 字段，该字段指向可能有助于您解决错误的某些内容。

[[HTTPRedirects]]
=== HTTP redirects

API v3 uses HTTP redirection where appropriate.
Clients should assume that any request may result in a redirection.
Receiving an HTTP redirection is not an error and clients should follow that redirect.
Redirect responses will have a `Location` header field which contains the URI of the resource to which the client should repeat the requests.

[%header,cols=2*]
|===
|Status Code
|Description

|301
|Permanent redirection. The URI you used to make the request has been superseded by the one specified in the `Location` header field. This and all future requests to this resource should be directed to the new URI.

|302, 307
|Temporary redirection. The request should be repeated verbatim to the URI specified in the `Location` header field but clients should continue to use the original URI for future requests.
|===

Other redirection status codes may be used in accordance with the HTTP 1.1 spec.

[[HTTPVerbs]]
=== HTTP verbs

Where possible, API v3 strives to use appropriate HTTP verbs for each action.

[%header,cols=2*]
|===
|Verb
|Description

|HEAD
|Can be issued against any resource to get just the HTTP header info.

|GET
|Used for retrieving resources.

|POST
|Used for creating resources.

|PATCH
|Used for updating resources with partial JSON data. For instance, an Issue resource has title and body attributes. A PATCH request may accept one or more of the attributes to update the resource. PATCH is a relatively new and uncommon HTTP verb, so resource endpoints also accept POST requests.

|PUT
|Used for replacing resources or collections. For PUT requests with no body attribute, be sure to set the Content-Length header to zero.

|DELETE
|Used for deleting resources.
|===

[[Hypermedia]]
=== Hypermedia

All resources may have one or more `*_url` properties linking to other resources.
These are meant to provide explicit URLs so that proper API clients don't need to construct URLs on their own.
It is highly recommended that API clients use these.
Doing so will make future upgrades of the API easier for developers.
All URLs are expected to be proper
http://tools.ietf.org/html/rfc6570[RFC 6570]
URI templates.

You can then expand these templates using something like the
https://github.com/hannesg/uri_template[uri_template]
gem:

....
>> tmpl = URITemplate.new('/notifications{?since,all,participating}')
>> tmpl.expand
=> "/notifications"

>> tmpl.expand :all => 1
=> "/notifications?all=1"

>> tmpl.expand :all => 1, :participating => 1
=> "/notifications?all=1&participating=1"
....

[[Pagination]]
=== Pagination

Requests that return multiple items will be paginated to 30 items by default.
You can specify further pages with the `?page` parameter.
For some resources, you can also set a custom page size up to 100 with the `?per_page` parameter.
Note that for technical reasons not all endpoints respect the `?per_page` parameter, see
https://developer.github.com/v3/activity/events/[events]
for example.

....
curl 'https://api.github.com/user/repos?page=2&per_page=100'
....

Note that page numbering is 1-based and that omitting the `?page` parameter will return the first page.

For more information on pagination, check out our guide on
https://developer.github.com/guides/traversing-with-pagination[Traversing with Pagination]
.

==== Link header

NOTE: It's important to form calls with Link header values instead of constructing your own URLs.

The
http://tools.ietf.org/html/rfc5988[Link header]
includes pagination information:

....
Link: <https://api.github.com/user/repos?page=3&per_page=100>; rel="next",
  <https://api.github.com/user/repos?page=50&per_page=100>; rel="last"
....

The example includes a line break for readability.

This `Link` response header contains one or more
https://developer.github.com/v3/#hypermedia[Hypermedia]
link relations, some of which may require expansion as
http://tools.ietf.org/html/rfc6570[URI templates]
.

The possible `rel` values are:

[%header,cols=2*]
|===
|Name
|Description

|next
|The link relation for the immediate next page of results.

|last
|The link relation for the last page of results.

|first
|The link relation for the first page of results.

|prev
|The link relation for the immediate previous page of results.
|===

[[RateLimiting]]
=== Rate limiting

For API requests using Basic Authentication or OAuth, you can make up to 5000 requests per hour.
Authenticated requests are associated with the authenticated user, regardless of whether
https://developer.github.com/v3/#basic-authentication[Basic Authentication]
 or an
 https://developer.github.com/v3/#oauth2-token-sent-in-a-header[OAuth token]
  was used.
This means that all OAuth applications authorized by a user share the same quota of 5000 requests per hour when they authenticate with different tokens owned by the same user.

For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

Note that
https://developer.github.com/v3/search/#rate-limit[the Search API has custom rate limit rules]
.

The returned HTTP headers of any API request show your current rate limit status:

....
curl -i https://api.github.com/users/octocat

HTTP/1.1 200 OK
Date: Mon, 01 Jul 2013 17:27:06 GMT
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 56
X-RateLimit-Reset: 1372700873
....

[%header,cols=2*]
|===
|Header Name
|Description

|X-RateLimit-Limit
|The maximum number of requests you're permitted to make per hour.

|X-RateLimit-Remaining
|The number of requests remaining in the current rate limit window.

|X-RateLimit-Reset
|The time at which the current rate limit window resets in
http://en.wikipedia.org/wiki/Unix_time[UTC epoch seconds]
.
|===

If you need the time in a different format, any modern programming language can get the job done. For example, if you open up the console on your web browser, you can easily get the reset time as a JavaScript Date object.

....
new Date(1372700873 * 1000)
// => Mon Jul 01 2013 13:47:53 GMT-0400 (EDT)
....

If you exceed the rate limit, an error response returns:

....
HTTP/1.1 403 Forbidden
Date: Tue, 20 Aug 2013 14:50:41 GMT
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1377013266
{
   "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
   "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
....

You can
https://developer.github.com/v3/rate_limit[check your rate limit status]
 without incurring an API hit.

==== Increasing the unauthenticated rate limit for OAuth applications

If your OAuth application needs to make unauthenticated calls with a higher rate limit, you can pass your app's client ID and secret as part of the query string.

....
curl -i 'https://api.github.com/users/whatever?client_id=xxxx&client_secret=yyyy'
HTTP/1.1 200 OK
Date: Mon, 01 Jul 2013 17:27:06 GMT
Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4966
X-RateLimit-Reset: 1372700873
....

NOTE: Never share your client secret with anyone or include it in client-side browser code. Use the method shown here only for server-to-server calls.

==== Staying within the rate limit

If you exceed your rate limit using Basic Authentication or OAuth, you can likely fix the issue by caching API responses and using
https://developer.github.com/v3/#conditional-requests[conditional requests]
.

==== Abuse rate limits

In order to provide quality service on GitHub, additional rate limits may apply to some actions when using the API. For example, using the API to rapidly create content, poll aggressively instead of using webhooks, make multiple concurrent requests, or repeatedly request data that is computationally expensive may result in abuse rate limiting.

Abuse rate limits are not intended to interfere with legitimate use of the API.
Your normal
https://developer.github.com/v3/#rate-limiting[rate limits]
 should be the only limit you target.
To ensure you're acting as a good API citizen, check out our
https://developer.github.com/guides/best-practices-for-integrators/[Best Practices guidelines].

If your application triggers this rate limit, you'll receive an informative response:

....
HTTP/1.1 403 Forbidden
Content-Type: application/json; charset=utf-8
Connection: close
{
  "message": "You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.",
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits"
}
....

[[UserAgentRequired]]
=== User agent required

All API requests MUST include a valid `User-Agent` header.
Requests with no `User-Agent` header will be rejected.
We request that you use your GitHub username, or the name of your application, for the `User-Agent` header value.
This allows us to contact you if there are problems.

Here's an example:

....
User-Agent: Awesome-Octocat-App
....

cURL sends a valid `User-Agent` header by default. If you provide an invalid `User-Agent` header via cURL (or via an alternative client), you will receive a `403 Forbidden` response:

....
curl -iH 'User-Agent: ' https://api.github.com/meta
HTTP/1.0 403 Forbidden
Connection: close
Content-Type: text/html
Request forbidden by administrative rules.
Please make sure your request has a User-Agent header.
Check https://developer.github.com for other possible causes.
....

[[ConditionalRequests]]
=== Conditional requests

Most responses return an `ETag` header. Many responses also return a `Last-Modified` header. You can use the values of these headers to make subsequent requests to those resources using the `If-None-Match` and `If-Modified-Since` headers, respectively. If the resource has not changed, the server will return a `304 Not Modified`.

NOTE: Making a conditional request and receiving a 304 response does not count against your Rate Limit, so we encourage you to use it whenever possible.

....
curl -i https://api.github.com/user
HTTP/1.1 200 OK
Cache-Control: private, max-age=60
ETag: "644b5b0155e6404a9cc4bd9d8b1ae730"
Last-Modified: Thu, 05 Jul 2012 15:31:30 GMT
Status: 200 OK
Vary: Accept, Authorization, Cookie
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4996
X-RateLimit-Reset: 1372700873
curl -i https://api.github.com/user -H 'If-None-Match: "644b5b0155e6404a9cc4bd9d8b1ae730"'
HTTP/1.1 304 Not Modified
Cache-Control: private, max-age=60
ETag: "644b5b0155e6404a9cc4bd9d8b1ae730"
Last-Modified: Thu, 05 Jul 2012 15:31:30 GMT
Status: 304 Not Modified
Vary: Accept, Authorization, Cookie
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4996
X-RateLimit-Reset: 1372700873
curl -i https://api.github.com/user -H "If-Modified-Since: Thu, 05 Jul 2012 15:31:30 GMT"
HTTP/1.1 304 Not Modified
Cache-Control: private, max-age=60
Last-Modified: Thu, 05 Jul 2012 15:31:30 GMT
Status: 304 Not Modified
Vary: Accept, Authorization, Cookie
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4996
X-RateLimit-Reset: 1372700873
....

[[CrossOriginResourceSharing]]
=== Cross origin resource sharing

The API supports Cross Origin Resource Sharing (CORS) for AJAX requests from any origin. You can read the
http://www.w3.org/TR/cors/[CORS W3C Recommendation]
, or
http://code.google.com/p/html5security/wiki/CrossOriginRequestSecurity[this intro]
 from the HTML 5 Security Guide.

Here's a sample request sent from a browser hitting `http://example.com`:

....
curl -i https://api.github.com -H "Origin: http://example.com"
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
....

This is what the CORS preflight request looks like:

....
curl -i https://api.github.com -H "Origin: http://example.com" -X OPTIONS
HTTP/1.1 204 No Content
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, X-GitHub-OTP, X-Requested-With
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Max-Age: 86400
....

[[JSON-PCallbacks]]
=== JSON-P callbacks

You can send a `?callback` parameter to any GET call to have the results wrapped in a JSON function. This is typically used when browsers want to embed GitHub content in web pages by getting around cross domain issues. The response includes the same data output as the regular API, plus the relevant HTTP Header information.

....
curl https://api.github.com?callback=foo
/**/foo({
  "meta": {
    "status": 200,
    "X-RateLimit-Limit": "5000",
    "X-RateLimit-Remaining": "4966",
    "X-RateLimit-Reset": "1372700873",
    "Link": [ // pagination headers and other links
      ["https://api.github.com?page=2", {"rel": "next"}]
    ]
  },
  "data": {
    // the data
  }
})
....

You can write a JavaScript handler to process the callback. Here's a minimal example you can try out:

....
<html>
<head>
<script type="text/javascript">
function foo(response) {
  var meta = response.meta;
  var data = response.data;
  console.log(meta);
  console.log(data);
}

var script = document.createElement('script');
script.src = 'https://api.github.com?callback=foo';

document.getElementsByTagName('head')[0].appendChild(script);
</script>
</head>

<body>
  <p>Open up your browser's console.</p>
</body>
</html>
....

All of the headers are the same String value as the HTTP Headers with one notable exception: Link. Link headers are pre-parsed for you and come through as an array of `[url, options]` tuples.

A link that looks like this:

....
Link: <url1>; rel="next", <url2>; rel="foo"; bar="baz"
....

+...+ will look like this in the Callback output:

....
{
  "Link": [
    [
      "url1",
      {
        "rel": "next"
      }
    ],
    [
      "url2",
      {
        "rel": "foo",
        "bar": "baz"
      }
    ]
  ]
}
....


[[Timezones]]
=== Timezones

Some requests allow for specifying timestamps or generate timestamps with time zone information. We apply the following rules, in order of priority, to determine timezone information for API calls.

==== Explicitly provide an ISO 8601 timestamp with timezone information

For API calls that allow for a timestamp to be specified, we use that exact timestamp. An example of this is the
https://developer.github.com/v3/git/commits[Commits API]
.

These timestamps look something like `2014-02-27T15:05:06+01:00`. Also see
https://developer.github.com/v3/git/commits/#example-input[this example]
 for how these timestamps can be specified.

==== Using the `Time-Zone` header

It is possible to supply a `Time-Zone` header which defines a timezone according to the
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[list of names from the Olson database]
.

....
curl -H "Time-Zone: Europe/Amsterdam" -X POST https://api.github.com/repos/github/linguist/contents/new_file.md
....

This means that we generate a timestamp for the moment your API call is made in the timezone this header defines.
For example, the
https://developer.github.com/v3/repos/contents/[Contents API]
 generates a git commit for each addition or change and uses the current time as the timestamp. This header will determine the timezone used for generating that current timestamp.

==== Using the last known timezone for the user

If no `Time-Zone` header is specified and you make an authenticated call to the API, we use the last known timezone for the authenticated user. The last known timezone is updated whenever you browse the GitHub website.

==== UTC

If the steps above don't result in any information, we use UTC as the timezone to create the git commit.


